### ISSUE TITLE
Is this Wekinator, or a related project?

### ISSUE THREAD

**Issue by lpil** [fiebrink1/wekimini#2]
Hello!

I'm a little confused by README of this project, and some the content of Wekinator website. The site directs us here to find the source, yet this repo seems to be much younger than the Wekinator project, and is "mini".

Is this the Wekinator project you started in 2009? If not, what is it?

Thanks,
Louis

**Comment by fiebrink1** [comment]
Hi Louis, thanks for the question! To make a long story short, yes, this is Wekinator. 

To explain: this code base began as a very small re-implementation of some of the original Wekinator's functionality. But it turned into a complete re-implementation of all the main features, in a more stable and better organised code base, and has now made the old Wekinator redundant. I've been on the fence about whether to rename the git repo to reflect that.

Anyway, your confusion is totally warranted. I should update the README to make this clear. Any opinion on changing the repo name at this late stage?

**Comment by lpil** [comment]
Ah, thanks. Good to know. :)

Perhaps rename it to Wekinator 2?
