### ISSUE TITLE
feature request: set class/gesture/numeric value via OCS

### ISSUE THREAD

**Issue by jango-fx** [fiebrink1/wekimini#26]
if i'm correct it's currently not possible to select the class/gesture/value via OSC to automate the recording process.
in my mind, that's the main missing control feature to be able run a project completely automated.

which relates to #25: running headless.

I'd love to contribute myself, but i'm not sure i am able to work my way through Wekinators code structure on my own… 😅

**Comment by Louismac** [comment]
Try this?

"/wekinator/control/outputs (with list of floats): Send Wekinator current output values to populate the boxes/sliders on its GUI. Attach one float per output, in order."

http://www.wekinator.org/detailed-instructions/#Controlling_Wekinator_via_OSC_messages

**Comment by jango-fx** [comment]
🙈 omg, i'm sorry, i don't know how i could have missed that

**Comment by jango-fx** [comment]
thanks for that super quick reply though! 🙏
