### ISSUE TITLE
Document project setup, running of test suite, etc

### ISSUE THREAD

**Issue by lpil** [fiebrink1/wekimini#4]
Hello!

I believe all good open source projects need documentation. Could we possible add some useful information to the README?

I was thinking it would be good to start with these:
- [ ] Introduction to the project purpose
- [ ] Basic developer setup
- [ ] How to run the test suite
- [ ] Licence & contributing information

Thanks,
Louis

**Comment by q2dg** [comment]
Hello?

**Comment by fiebrink1** [comment]
I haven't had any time to do this yet but this is noted.

**Comment by lpil** [comment]
This problem doesn't seem to be resolved. Is this a wontfix ?
