### ISSUE TITLE
Add the ability to delete all examples for a specific model with OSC

### ISSUE THREAD

**Issue by Nagasaki45** [fiebrink1/wekimini#6]
This option is available in the GUI. I can't see a reason against adding it to the OSC control interface.

I will try to handle it myself and submit a PR.

**Comment by fiebrink1** [comment]
This is possible to do already -- use the "X" in the row of the model (rather than the "X" button on top which deletes all examples)

**Comment by Nagasaki45** [comment]
I probably wasn't clear enough. I want an OSC endpoint for controlling this functionality. Something like `/wekinator/control/deleteModelExamples` with an `int` argument for the model number.

**Comment by fiebrink1** [comment]
Ahh got it. This is probably easier for me to just do rather than verify a PR. Give me 10 minutes

**Comment by fiebrink1** [comment]
OK, thanks for the suggestion! I just added this. Should work with message /wekinator/control/deleteExamplesForOutput using output indexed starting with 1.

**Comment by Nagasaki45** [comment]
Thanks for the fix - 41493cc79aa1d799354d3dd090ccb6df0d293848 (adding the comment just for reference).
I think we can close the ticket.

**Comment by fiebrink1** [comment]
Thanks!
